apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: thunder
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/ayeshajay/thunder  # TODO: update to actual repo URL
  ref:
    branch: add-thunder-gitops-artifacts
